name: build-dicom-dicomweb-proxy

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:

  build-dicom-dicomweb-proxy:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker (orthanc-dicom-dicomweb-proxy)
        id: meta-orthanc-dicom-dicomweb-proxy
        uses: docker/metadata-action@v4
        with:
          images: orthancteam/orthanc-dicom-dicomweb-proxy
          labels: |
            org.opencontainers.image.title=orthanc-dicom-dicomweb-proxy
            org.opencontainers.image.vendor=Orthanc Team SRL

      - name: Build and push orthanc-dicom-dicomweb-proxy Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta-orthanc-dicom-dicomweb-proxy.outputs.tags }}
          labels: ${{ steps.meta-orthanc-dicom-dicomweb-proxy.outputs.labels }}

      - name: Docker Hub Description (orthanc-dicom-dicomweb-proxy)
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: orthancteam/orthanc-dicom-dicomweb-proxy
          short-description: A regular Orthanc acting as a DICOM to DICOMweb proxy.
          readme-filepath: README.md
